#
# Makefile to support asd boards
#

obj-$(CONFIG_MACH_MESON6_PI3100) += board-m6g24_pi3100.o
obj-$(CONFIG_MACH_MESON6_PI3100) += board-m6g24_pi3100-panel.o
obj-$(CONFIG_MACH_MESON6_PI3900) += board-m6g24_pi3900.o
obj-$(CONFIG_MACH_MESON6_PI3900) += board-m6g24_pi3900-panel.o

