#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_SENSORS_MMA8452)   += mma8452.o
obj-$(CONFIG_SENSORS_MMA7660)   += mma7660.o
obj-$(CONFIG_SENSORS_LIS3DH)   += lis3dh_acc.o
obj-$(CONFIG_SENSORS_MMC328x)   += mmc328x.o
obj-$(CONFIG_ECOMPASS)          += mecs.o
obj-$(CONFIG_BOSCH_BMA250)      += bma250.o
obj-$(CONFIG_BOSCH_BMA250_MEMSIC)      += bma250_memsic.o
obj-$(CONFIG_BOSCH_BMA222)      += bma222.o
obj-$(CONFIG_SENSORS_MC32X0)   += mc32x0.o
obj-$(CONFIG_SENSORS_DMARD06)	+= dmard06.o
obj-$(CONFIG_SENSORS_AFA750)      += afa750.o
obj-$(CONFIG_CALI_NEGATIVE)      += afa750_cali_i2c.o
obj-$(CONFIG_CALI_POSITIVE)      += afa750_cali_i2c_positive.o
obj-$(CONFIG_SENSORS_MMA865X)	+= mma865x.o
obj-$(CONFIG_SENSORS_CM36283)	+= cm36283.o
obj-$(CONFIG_SENSORS_CM3232)	+= cm3232.o
obj-$(CONFIG_SENSORS_MMC328xMA)   += mmc328x.o
obj-$(CONFIG_SENSORS_LSM303D)	+= lsm303d.o
obj-$(CONFIG_LIGHTSENSOR_EPL6814)+= elan_epl6814.o
obj-$(CONFIG_SENSORS_STK8313)	+= stk831x.o
obj-$(CONFIG_SENSORS_STK8312)	+= stk831x.o
obj-$(CONFIG_SENSORS_DMARD10)	+= dmt10.o
obj-$(CONFIG_SENSORS_KXTJ9)	+= kionix_accel.o
obj-$(CONFIG_SENSORS_LTR501)	+= ltr501_als.o
obj-$(CONFIG_MPU3050_v4_1_2)		+= inv_mpu/
obj-$(CONFIG_SENSORS_MM3A310)	+= mm3a310.o
