#
# Makefile for the amlogic spi nor flash bus drivers.
#

obj-$(CONFIG_AMLOGIC_SPI_NOR)	+= spi_nor.o
obj-$(CONFIG_AMLOGIC_SPI_NOR)	+= apollo_spi_nor.o
obj-$(CONFIG_SPI_NOR_SECURE_STORAGE)	+= spi_secure_storage.o
